### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by chuck-alt-delete** [chuck-alt-delete/blog-source#1]
let's see the traffic. See https://gideonwolfe.com/posts/sysadmin/hugo/hugogoogleanalytics/

**Comment by chuckinator0** [comment]
Google analytics: G-S20RBCMJWE

**Comment by chuck-alt-delete** [comment]
See this one too for the new Google analytics 4: https://gist.github.com/zjeaton/42246742cdaf2fb46400d04c2eba9a8a

**Comment by chuck-alt-delete** [comment]
Should work now
